<h1>Creating Tables in SQLite Studio following Relational Model<h/1>

In [1]:
import sqlite3

In [10]:
sql_db_connection = sqlite3.connect(r"C:\Users\14087\Downloads\sqlitestudio-3.3.3\SQLiteStudio\Hotel_Bookings_Data.db")
cursor = sql_db_connection.cursor()

cursor.execute("DROP TABLE IF EXISTS Hotel_Booking_Transaction_Table")

create_transaction_table = """CREATE TABLE Hotel_Booking_Transaction_Table (
  is_canceled int1,
  lead_time int,
  arrival_date_year int,
  arrival_date_month varchar,
  arrival_date_week_number int,
  arrival_date_day_of_month int,
  stays_in_weekend_nights int,
  stays_in_week_nights int,
  adults int,
  children int,
  babies int,
  is_repeated_guest int1,
  previous_cancellations int,
  previous_booking_not_cancelled int,
  days_in_waiting_list int,
  adr int,
  required_car_parking_spaces int,
  total_of_special_requests int,
  reservation_status_date date,
  hotel_ID varchar,
  country_ID varchar,
  meal_ID varchar,
  market_ID varchar,
  distribution_channel_ID varchar,
  reserved_booking_ID varchar,
  assigned_booking_ID varcahr,
  deposit_ID varcahr,
  customer_ID varchar,
  reservation_status_ID varchar,
  agent_ID float,
  company_ID float
)"""
cursor.execute(create_transaction_table)

sql_db_connection.commit()
sql_db_connection.close()

In [8]:
sql_db_connection = sqlite3.connect(r"C:\Users\14087\Downloads\sqlitestudio-3.3.3\SQLiteStudio\Hotel_Bookings_Data.db")
cursor = sql_db_connection.cursor()

create_hotel_classification_table = """CREATE TABLE Hotel_Classification (
  hotel_ID varchar [pk],
  hotel_class varchar)
"""
cursor.execute(create_hotel_classification_table)

sql_db_connection.commit()
sql_db_connection.close()

In [17]:
sql_db_connection = sqlite3.connect(r"C:\Users\14087\Downloads\sqlitestudio-3.3.3\SQLiteStudio\Hotel_Bookings_Data.db")
cursor = sql_db_connection.cursor()

cursor.execute("DROP TABLE IF EXISTS Country")
cursor.execute("DROP TABLE IF EXISTS Meal_Classification")
cursor.execute("DROP TABLE IF EXISTS Market_Segment")
cursor.execute("DROP TABLE IF EXISTS Distribution_Channel")
cursor.execute("DROP TABLE IF EXISTS Reserved_Booking_Type")
cursor.execute("DROP TABLE IF EXISTS Assigned_Booking_Type")
cursor.execute("DROP TABLE IF EXISTS Deposit_Booking_Type")
cursor.execute("DROP TABLE IF EXISTS Customer_Classification")
cursor.execute("DROP TABLE IF EXISTS Reservation_Status_Classification")
cursor.execute("DROP TABLE IF EXISTS Agent_Table")
cursor.execute("DROP TABLE IF EXISTS Company_Table")


create_country_table = """CREATE TABLE Country (
  country_ID int [pk],
  country varchar)
"""

create_meal_classification_table = """CREATE TABLE Meal_Classification (
  meal_ID varchar [pk],
  meal varchar)
"""

create_market_segment_table = """CREATE TABLE Market_Segment (
  market_ID varcahr [pk],
  market_segment varcahr)
"""

create_distribution_channel_table = """CREATE TABLE Distribution_Channel (
  distribution_channel_ID varcahr [pk],
  distribution_channel varchar)
"""

create_reserved_booking_table = """CREATE TABLE Reserved_Booking_Type (
  reserved_booking_ID varchar [pk],
  reserved_booking_type varchar)
"""

create_assigned_booking_table = """CREATE TABLE Assigned_Booking_Type (
  assigned_booking_ID varchar [pk],
  assigned_booking_ID_booking_type varchar)
"""

create_deposit_booking_table = """CREATE TABLE Deposit_Booking_Type (
  deposit_ID varchar [pk],
  deposit_booking_type varchar)
"""

create_customer_classification_table = """CREATE TABLE Customer_Classification (
  customer_ID varchar [pk],
  customer_type varchar)
"""

create_reservation_status_classification_table = """CREATE TABLE Reservation_Status_Classification (
  reservation_status_ID varchar [pk],
  reservation_status varchar)
"""

create_agent_table = """CREATE TABLE Agent_Table (
  agent_ID float [pk],
  agent varchar)
"""

create_company_table = """CREATE TABLE Company_Table (
  company_ID float [pk],
  company varchar)
"""

cursor.execute(create_country_table)
cursor.execute(create_meal_classification_table)
cursor.execute(create_market_segment_table)
cursor.execute(create_distribution_channel_table)
cursor.execute(create_reserved_booking_table)
cursor.execute(create_assigned_booking_table)
cursor.execute(create_deposit_booking_table)
cursor.execute(create_customer_classification_table)
cursor.execute(create_reservation_status_classification_table)
cursor.execute(create_agent_table)
cursor.execute(create_company_table)

sql_db_connection.commit()
sql_db_connection.close()

In [18]:
###So I created the data model, which normalizes this relational database model that best I could. The transformations 
###would include creating additional primary key columns and would need additional data sources (ie. country code data).
###After creating the data model and writing it the sqlite database, I could transform the data, load my pandas dataframes into
###a sqlite table, and then rejoin these tables as a compelte view.

<h3>I understand the ETL ideas conceptually, however I already have a full view of the dataset I can use for analysis.
Creating a relational database model and going through the process of normalization will allow the database to be optimized for
OLAP purposes. My actual ETL process was simply to download a CSV file, and load it into SqLite in sqlstudio. I'm ready to
move into part 3 of this case study.<h/3>